spring:
  datasource:
    url: jdbc:mysql://192.168.8.110:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.8.110
    port: 6379
    password: root
    timeout: 6000ms
    lettuce:
      pool:
        max-idle: 300
        min-idle: 5
        max-active: 1000
        max-wait: 20000ms

distributed:
  lock:
    wait-time: 3000
    lease-time: 30000
    retry-interval: 100
    primary-executor: com.oceancloud.grampus.common.lock.strategy.RedisTemplateLockStrategy

#grampus:
  #  security:
  #    token:
  #      secret-key: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
grampus:
  auth:
    token:
      secret:
        key: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
      expire:
        seconds: 150000
    system:
      type: system
      ignoreUrls:
        - "/favicon.ico"
        - "/error"
        - "/static/**"
        - "/webjars*"
        - "/webjars/**"
        - "/auth/captcha"
        - "/auth/public-key"
        - "/upload/**"
        - "/swagger-resources/**"
        - "/v2/api-docs"
        - "/v3/api-docs"
        - "/doc.html"
        - "/system/register/**"
        - "/system/login"
        - "/demo/**"

#    datasource:
#      names: master,slave0
#      master:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#      slave0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#    sharding:
#      master-slave-rules:
#        ds0:
#          master-data-source-name: master
#          slave-data-source-names: slave0
#    props:
#      sql.show: false

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:28070/xxl-job-admin
    executor:
      address: ''
      appname: ${spring.application.name}
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999