spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1

grampus:
  security:
    token:
      secret-key: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
  auth:
    token:
      secret:
        key: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
      expire:
        seconds: 150000
    system:
      type: system
      ignoreUrls:
        - /register/**
#    datasource:
#      names: master,slave0
#      master:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#      slave0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/grampus_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#    sharding:
#      master-slave-rules:
#        ds0:
#          master-data-source-name: master
#          slave-data-source-names: slave0
#    props:
#      sql.show: false
