server:
  port: 28080

spring:
  profiles:
    active: "@profiles.active@"
  application:
    name: "@artifactId@"

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  # 搜索指定包别名
  typeAliasesPackage: com.vdegree.grampus.*.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:/mapper/**/*.xml

# mybatis增强配置
mapper:
  not-empty: false
  style: camelhump
  identity: MYSQL
  wrap-keyword: "`{0}`"
  safe-delete: true
  safe-update: true
  idgenerator:
    snowflake:
      dataCenterId: 8
      workerId: 4

# PageHelper分页插件
pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
