server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@

mapper:
  idgenerator:
    snowflake:
      workerId: 4
      dataCenterId: 8
